### ISSUE TITLE
Please publish new version

### ISSUE THREAD

**Issue by ebaauw** [abandonware/node-bluetooth-hci-socket#30]
Could you please publish a new version with the latest commits (notably https://github.com/abandonware/node-bluetooth-hci-socket/commit/8ddae50a67a70055fc557b9b4d0122aae665a2c2, which gets rids of the deprecation warnings when installing).

I ended up publishing local forks for noble and node-bluetooth-hci-socket, because I feared these libraries were no longer maintained, but I saw a recent PR being merged by @rzr into noble.

I really appreciate the work you're doing here and am more than willing to help where I can.

**Comment by rzr** [comment]
It's done:
https://www.npmjs.com/package/@abandonware/bluetooth-hci-socket/v/0.5.3-8

Please confirm it's working as expected and close this thread.

And eventually report this on upstream tracker, ie:
https://github.com/noble/node-bluetooth-hci-socket/issues/123

**Comment by ebaauw** [comment]
Thanks for the quick response.  As far as I can tell it's working.  I've updated my PR on noble (https://github.com/abandonware/noble/pull/224) to use this version.

How do I report this on the upstream tracker?

**Comment by rzr** [comment]
maybe duplicate the ticket or just comment https://github.com/noble/node-bluetooth-hci-socket/pull/122 to tell they are desirable
