### ISSUE TITLE
Rebuild not possible 

### ISSUE THREAD

**Issue by Apollon77** [abandonware/node-bluetooth-hci-socket#38]
I did some nodejs upgrade tests and had bigger issues getting bluetooth-hci-socket rebuilded because by default it simply told

> [@abandonware/bluetooth-hci-socket] Success: "/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node" already installed
> Pass --update-binary to reinstall or --build-from-source to recompile

I tried many things and did a bigger research. There is no way to add more parameters to the "nom rebuild" command, so in the end "npm i" would be the only option (with other side effects).

In fact I ended up in adding "--update-binary" to the "install script" and with this a rebuild was successful too ...

**Comment by Apollon77** [comment]
@rzr Any advice?

**Comment by rzr** [comment]
npm install  --global npm-check-updates

**Comment by Apollon77** [comment]
@rzr it is not about finding updateable deps ... it i about the lock file and the version ... I can do the release PR but then it will have an updated lock file version (alnd also the abve script will not change that). is this acceptable?

**Comment by Apollon77** [comment]
@rzr sorry to bother you again ... if it is ok that I update package lock to npm 8 then I can do the PR ... what's your opinion?

**Comment by rzr** [comment]
yea sure try it , and look at history to create a PR to make a new release !
