### ISSUE TITLE
Cannot find module '@abandonware/bluetooth-hci-socket'

### ISSUE THREAD

**Issue by Skol6** [abandonware/node-bluetooth-hci-socket#43]
Hi,

IObroker always states the following error:

`Cannot find module '@abandonware/bluetooth-hci-socket' Require stack: - /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js - /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js - /opt/iobroker/node_modules/@abandonware/noble/lib/resolve-bindings.js - /opt/iobroker/node_modules/@abandonware/noble/index.js - /opt/iobroker/node_modules/iobroker.ble/build/scanProcess.js`

But everything is installed properly and the files are in the path as requested.
Any ideas?

**Comment by Apollon77** [comment]
Then please remoce and reinstall the adapter in ioBroker/the npm module of the adapter

**Comment by Skol6** [comment]
Hi, already tried.
there is no change at all.
Using hciconfig I can start scanning and there all BLE devices can be seen, but no possibilty to get them running in IObroker :(

**Comment by Skol6** [comment]
Performed a clean new install. Now everything is working fine...
